using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PartyUp.Models
{
    /*
    This is the event that will be represented in the data containing basic details
    regarding location and event details. The database will reflect what is presented
    in this model. Many to many relationship is broken by the attendance table. 
    */
    public class Event
    {
        //unique id generated by the database; used for CRUD operations
        public int EventId { get; set; }
        //The official name set by the user
        public string Name { get; set; }
        //The time that the event will take place
        public DateTime EventDateTime { get; set; }
        //Details about the event the users wishes to include
        public string Details { get; set; }
        //Street address
        public string Address1 { get; set; }
        //apartment or unique id apart from standard address
        public string Address2 { get; set; }
        //city that the event will take place in
        public string City { get; set; }
        //stat that the event will take place in
        public string State { get; set; }
        //the country that the event will take place in
        //most will be set null consider our audience
        public string Country { get; set; }
        //The zip or postal code the event will take place in
        public string PostalCode { get; set; }
        //the precise gps latitude
        public string Latitude { get; set; }
        //the precise gps longitude
        public string Longitude { get; set; }
        //the owner of the event
        public ApplicationUser User { get; set; }
        //all of the users who are invited to the event
        public virtual ICollection<Attendance> Attendeees { get; set; }
    }
}